[tool.poetry]
name = "project-3"
version = "0.1.0"
description = ""
authors = ["Dmitry <k1791@mail.ru>"]
readme = "README.md"
packages = [{include = "project_3"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
